listenAddrs:
  - /ip4/0.0.0.0/tcp/0
discovery:
  serviceTag: p2pmq/kad
  mode: server
  bootstrappers:
    - /ip4/0.0.0.0/tcp/5001/p2p/12D3KooWH9DU2whKMyL4WXExj2iZNHmEfg5kDtBKWfmw4QGjJ1eV # change peer id
pubsub:
