listenAddrs:
  - /ip4/0.0.0.0/tcp/5101
discovery:
  serviceTag: p2pmq/kad
  mode: server
  bootstrappers:
    - /ip4/0.0.0.0/tcp/5001/p2p/12D3KooWNBpcEZvtNLkAuHf3RdsRcokeQQNc2WrgU7iHipwVAKWM # change peer id
# mdnsTag: p2pmq/mdns/test
pubsub:
