name: Examples

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "*" ]

jobs:

  gotest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Local DON Tests
      run: cd examples/don && go test -v -race .